# Generated by Django 3.0 on 2021-10-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0004_booking_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortTrick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=500)),
                ('ans', models.CharField(max_length=2000)),
                ('file', models.FileField(upload_to='Tricks')),
                ('sub', models.CharField(max_length=100)),
            ],
        ),
    ]
